// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCl2RlH2Yuh5L7ZlTsAaSyPi21KqD38yys',
    appId: '1:549469597315:web:34bccc14d5f2a68a7135b6',
    messagingSenderId: '549469597315',
    projectId: 'yankeepa-6502f',
    authDomain: 'yankeepa-6502f.firebaseapp.com',
    storageBucket: 'yankeepa-6502f.firebasestorage.app',
    measurementId: 'G-3RQR37EWWF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXJ-5nAkau8_51Mgox-cyNuZuW7IPsdQw',
    appId: '1:549469597315:android:de1eea394ea42a567135b6',
    messagingSenderId: '549469597315',
    projectId: 'yankeepa-6502f',
    storageBucket: 'yankeepa-6502f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGUo7TDFMQ1u7qonIi1_QwwTaFhfZRmck',
    appId: '1:549469597315:ios:276633913405b7c77135b6',
    messagingSenderId: '549469597315',
    projectId: 'yankeepa-6502f',
    storageBucket: 'yankeepa-6502f.firebasestorage.app',
    iosClientId: '549469597315-4nen9bkjdfimh5oo0n996kvvj1hfkpig.apps.googleusercontent.com',
    iosBundleId: 'com.ypa.restaurant',
  );
}
